# Generated by Django 3.1.4 on 2021-10-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('valid_upto', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
