# Generated by Django 3.1.4 on 2021-10-01 12:43

import datetime
from django.db import migrations, models
import django.utils.crypto


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(default=django.utils.crypto.get_random_string, max_length=20),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 10, 1, 18, 13, 37, 181517)),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_upto',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 10, 1, 19, 13, 37, 181517)),
        ),
    ]
