# Generated by Django 3.1.4 on 2021-10-01 12:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Group name')),
                ('kind', models.CharField(choices=[('PERSONAL', 'personal'), ('MULTIPLE', 'multiple')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validity', models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 10, 31, 18, 13, 37, 177997))),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Plan')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('has_referal', models.BooleanField(default=False)),
                ('member_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='membership.group')),
            ],
        ),
    ]
