# Generated by Django 3.1.4 on 2021-10-01 13:00

import datetime
from django.db import migrations, models
import django.utils.crypto


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='slug',
            field=models.SlugField(blank=True, default=django.utils.crypto.get_random_string, unique=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='title',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Plan name'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='validity',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 10, 31, 18, 30, 42, 711128)),
        ),
    ]
